### ISSUE TITLE
Typo: `INSUFFICENT_PERMISSIONS'

### ISSUE THREAD

**Issue by fukanchik** [kata198/usrsvc#3]
https://github.com/kata198/usrsvc/blob/master/usrsvcmod/Program.py#L239
https://github.com/kata198/usrsvc/blob/master/usrsvcmod/Program.py#L248

INSUFFICIENT_PERMISSIONS = 136 
should be used

**Comment by kata198** [comment]
Another good find. Not sure why my pylint/pyflakes wouldn't report on this. And my usage never hit those lines. I should learn to spell. Anyway fixed.
